{ config, pkgs, ... }: {
  home.packages = with pkgs; [
    (pkgs.emacsWithPackagesFromUsePackage {
      config = ./emacs.el;
      defaultInitFile = true;
      # package = pkgs.emacs-macport;
      package = pkgs.emacs-git;
      alwaysEnsure = true;
      extraEmacsPackages = epkgs: [
        epkgs.vterm
        epkgs.transient
        epkgs.notmuch
        epkgs.mu4e
        epkgs.pdf-tools
        (epkgs.treesit-grammars.with-grammars (grammars:
          with grammars; [
            tree-sitter-bash
            tree-sitter-css
            tree-sitter-dockerfile
            tree-sitter-elisp
            tree-sitter-go
            tree-sitter-php
            tree-sitter-elixir
            tree-sitter-heex
            tree-sitter-html
            tree-sitter-javascript
            tree-sitter-json
            tree-sitter-nix
            tree-sitter-ruby
            tree-sitter-rust
            tree-sitter-toml
            tree-sitter-tsx
            tree-sitter-typescript
            tree-sitter-yaml
          ]))
      ];
    })
    aerc
    gopls
    nixos-rebuild
    zls
    zig
    poppler
    ffmpegthumbnailer
    mediainfo
    thefuck
    imagemagick
    yubikey-manager
    clojure
    colima
    localsend
    delta
    starship
    devenv
    bat
    fd
    hledger
    ledger
    wezterm
    swc
    dive
    tree
    tshark
    act
    cmake
    netcat
    catgirl
    zathura
    docker-client
    jq
    ytfzf
    gitflow
    got
    wget
    postgresql
    coreutils
    terraform
    caddy
    bun
    nest-cli
    kubernetes-helm
    kubeseal
    packer
    qemu
    kustomize
    k9s
    kubectl
    krew
    mblaze
    argocd
    kubernetes-helm
    cowsay
    hexedit
    spicetify-cli
    ffmpeg
    untrunc-anthwlock
    ansible
    openssl
    yamllint
    kubo
    gnumake42
    libqalculate
    lazygit
    mg
    k6
    swaks
    ngrok
    nodePackages.npm
    nodePackages.pnpm
    nodePackages.typescript
    nodePackages.npm-check-updates
    nodejs
    yarn
    perl
    openstackclient
    alacritty
    innernet
    wireguard-go
    wireguard-tools
    openvpn
    easyrsa
    nginx
    nmap
    meld
    android-tools
    tailscale
  ];  
}
