---
name: "MacOs Nix build"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        machine:
          - "aron"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: heph2
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix build .#darwinConfigurations.${{ matrix.machine }}.config.system.build.toplevel
