---
name: "Test"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        machine:
          - "aron"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix build .#darwinConfigurations.${{ matrix.machine }}.config.system.build.toplevel